#!/usr/bin/env python3
"""Phase 0 macOS sandbox spike -- the "target" script VBA Shell() invokes.

Purpose: prove that a Python process, launched from Excel for Mac's App
Sandbox via VBA `Shell()`, can write an .xlsx file to a normal user directory
outside the sandbox container, and that Excel can then be granted access to
open it (see spike/README.md and spike/vba/SpikeShell.bas for the full
procedure and PLANNING.md Section 7 for why this is de-risked first).

Deliberately standalone and dependency-light beyond openpyxl (already a
project runtime dependency): it must run correctly when invoked exactly the
way VBA `Shell()` will invoke the real CLI --  by an ABSOLUTE interpreter
path, from a non-login, non-interactive shell, with NO inherited PATH, shell
profile (.zshrc/.bash_profile), or meaningful cwd. Do not add any behavior
here that relies on those.

Usage:
    /absolute/path/to/venv/bin/python spike_target.py /absolute/output/dir

Writes "<output_dir>/spike_output.xlsx" containing:
    - a UTC timestamp (proves the file is freshly written, for the VBA
      poll-until-exists step)
    - sys.executable (proves which interpreter actually ran -- useful to
      confirm VBA's Shell() used the venv python we told it to, not a
      system python picked up some other way)
    - the effective working directory and a few environment sanity checks,
      for diagnosing sandbox-related surprises if the spike fails

Exit codes: 0 on success, 1 on any failure (bad args, write failure). Prints
the absolute path of the written file to stdout on success, which the VBA
side does not currently parse (it polls for the file instead, since VBA
Shell() is asynchronous and does not hand back stdout) but which is useful
for the manual `env -i` verification step in spike/README.md.
"""

from __future__ import annotations

import datetime
import os
import sys


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(
            f"usage: {argv[0] if argv else 'spike_target.py'} <absolute-output-dir>",
            file=sys.stderr,
        )
        return 1

    output_dir = argv[1]

    if not os.path.isabs(output_dir):
        print(f"error: output dir must be an absolute path, got {output_dir!r}", file=sys.stderr)
        return 1

    try:
        os.makedirs(output_dir, exist_ok=True)
    except OSError as exc:
        print(f"error: could not create output dir {output_dir!r}: {exc}", file=sys.stderr)
        return 1

    try:
        from openpyxl import Workbook
    except ImportError as exc:
        print(f"error: openpyxl not importable from this interpreter: {exc}", file=sys.stderr)
        return 1

    output_path = os.path.join(output_dir, "spike_output.xlsx")

    wb = Workbook()
    ws = wb.active
    ws.title = "Spike"
    ws["A1"] = "Generated by"
    ws["B1"] = "spike_target.py"
    ws["A2"] = "Timestamp (UTC)"
    ws["B2"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    ws["A3"] = "sys.executable"
    ws["B3"] = sys.executable
    ws["A4"] = "os.getcwd()"
    ws["B4"] = os.getcwd()
    ws["A5"] = "PATH env var present?"
    ws["B5"] = "yes" if os.environ.get("PATH") else "no (expected under env -i / sandboxed Shell())"
    ws["A6"] = "PID"
    ws["B6"] = os.getpid()

    try:
        wb.save(output_path)
    except OSError as exc:
        print(f"error: could not write {output_path!r}: {exc}", file=sys.stderr)
        return 1

    print(output_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
